import numpy as np
from sklearn import _final_estimator_has, pipeline
from sklearn.utils.metadataimport import (
    _routing_enabled,
    process_routing,
)
from sklearn.utils.metaestimators import available_if
from sklearn.utils.validation import check_is_fitted


class DistributionalRegressionPipeline(pipeline.Pipeline):
    """Pipeline of transforms with a final estimator that supports distributional regression."""

    @available_if(_final_estimator_has("predict_quantile"))
    def predict_quantile(
        self,
        X: np.ndarray,
        quantile: float | np.ndarray,
        **params,
    ) -> np.ndarray:
        """Transform the data, and apply `predict_quantile` with the final estimator.

        Call `transform` of each transformer in the pipeline. The transformed
        data are finally passed to the final estimator that calls `predict_quantile`
        method. Only valid if the final estimator implements `predict_quantile`.

        Parameters
        ----------
        X : iterable
            Data to predict on. Must fulfill input requirements of first step
            of the pipeline.

        quantile : float or array-like of shape (n_quantiles,)
            Quantile(s) to predict, which must be between 0 and 1 inclusive.

        Returns
        -------
        y_pred : ndarray
            Result of calling `predict_quantile` on the final estimator.
        """
        check_is_fitted(self)
        Xt = X

        if not _routing_enabled():
            for _, name, transform in self._iter(with_final=False):
                Xt = transform.transform(Xt)
            return self.steps[-1][1].predict_quantile(Xt, quantile=quantile)

        # metadata routing enabled
        routed_params = process_routing(
            self, "predict_quantile", quantile=quantile, **params
        )
        for _, name, transform in self._iter(with_final=False):
            Xt = transform.transform(Xt, **routed_params[name].transform)
        return self.steps[-1][1].predict_quantile(
            Xt, quantile=quantile, **routed_params[self.steps[-1][0]].predict
        )

    @available_if(_final_estimator_has("predict_distribution_parameters"))
    def predict_distribution_parameters(self, X: np.ndarray, **params):
        """Transform the data, and apply `predict_distribution_parameters` with the final estimator.

        Call `transform` of each transformer in the pipeline. The transformed
        data are finally passed to the final estimator that calls `predict_distribution_parameters`
        method. Only valid if the final estimator implements `predict_distribution_parameters`.

        Parameters
        ----------
        X : iterable
            Data to predict on. Must fulfill input requirements of first step
            of the pipeline.

        **params : dict of str -> object
            - If `enable_metadata_routing=False` (default): Parameters to the
              ``predict_distribution_parameters`` called at the end of all transformations in the pipeline.

            - If `enable_metadata_routing=True`: Parameters requested and accepted by
              steps. Each step must have requested certain metadata for these parameters
              to be forwarded to them.

            .. versionadded:: 0.20

            .. versionchanged:: 1.4
                Parameters are now passed to the ``transform`` method of the
                intermediate steps as well, if requested, and if
                `enable_metadata_routing=True` is set via
                :func:`~sklearn.set_config`.

            See :ref:`Metadata Routing User Guide <metadata_routing>` for more
            details.

            Note that while this may be used to return uncertainties from some
            models with ``return_std`` or ``return_cov``, uncertainties that are
            generated by the transformations in the pipeline are not propagated
            to the final estimator.

        Returns
        -------
        y_pred : ndarray
            Result of calling `predict_distribution_parameters` on the final estimator.
        """
        check_is_fitted(self)
        Xt = X

        if not _routing_enabled():
            for _, name, transform in self._iter(with_final=False):
                Xt = transform.transform(Xt)
            return self.steps[-1][1].predict_distribution_parameters(Xt, **params)

        # metadata routing enabled
        routed_params = process_routing(
            self, "predict_distribution_parameters", **params
        )
        for _, name, transform in self._iter(with_final=False):
            Xt = transform.transform(Xt, **routed_params[name].transform)
        return self.steps[-1][1].predict_distribution_parameters(
            Xt, **routed_params[self.steps[-1][0]].predict
        )
